version: "3.8"

services:
  top-rated-repositories:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment: 
      PORT: 3000
      NODE_ENV: development 
    depends_on:
      - redis  

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

# volumes:
#   redis-data: